"""Per-category 'current view' baseline, generated by Opus.

A baseline is a 200-400 word synthesis of the user's evolving view in a
category, derived from every bookmark in that category older than
BASELINE_AGE_DAYS. It anchors the model-update tier of the weekly digest:
each week, Opus is asked how the past 7 days' bookmarks shift, support,
contradict, or extend the baseline.

Baselines are versioned: every refresh inserts a new `category_views` row
rather than mutating the previous one. The most recent row per category
is the "live" baseline.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timedelta, timezone
from typing import Any

from anthropic import AsyncAnthropic
from pydantic import BaseModel
from sqlalchemy import desc, select
from sqlalchemy.ext.asyncio import AsyncSession

from twitter_bookmarks.config import get_settings
from twitter_bookmarks.db.models import (
    Author,
    Bookmark,
    BookmarkClassification,
    BookmarkThread,
    Category,
    CategoryView,
    Tweet,
)
from twitter_bookmarks.db.session import session_scope
from twitter_bookmarks.x_api.client import log_api_call

logger = logging.getLogger(__name__)

# Opus pricing as of April 2026. Confirm at https://www.anthropic.com/api.
OPUS_INPUT_PER_MTOK = 15.00
OPUS_OUTPUT_PER_MTOK = 75.00

BASELINE_TOOL = {
    "name": "record_baseline_view",
    "description": (
        "Record a 200-400 word synthesis of the user's evolving view in "
        "this category, based on the bookmarks they've saved over time. "
        "Structure it as: (a) what topics within this category they care "
        "about most, (b) the positions or framings they appear to favor, "
        "(c) the open questions or tensions they're tracking. Be "
        "specific — name people, claims, debates. Avoid vague summaries. "
        "If the corpus is too thin (under ~5 substantive bookmarks), set "
        "is_thin=true."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "is_thin": {
                "type": "boolean",
                "description": (
                    "True if the corpus is too thin for an honest baseline."
                ),
            },
            "view_text": {
                "type": "string",
                "description": (
                    "200-400 words. Markdown allowed. Three sections: "
                    "what topics they care about, positions they favor, "
                    "open questions/tensions."
                ),
            },
        },
        "required": ["is_thin", "view_text"],
    },
}


class _BaselinePayload(BaseModel):
    is_thin: bool
    view_text: str = ""


def _system_prompt(category: Category) -> str:
    from twitter_bookmarks.synopsis._style import WRITING_STYLE

    return (
        "You are reading the bookmarks one user has saved in a single "
        "category over time and writing their 'current view' — a "
        "200-400 word synthesis that captures: (a) the topics within "
        "this category they consistently engage with, (b) the positions "
        "or framings they appear to favor, (c) the open questions or "
        "tensions they're tracking.\n\n"
        f"CATEGORY: {category.name} ({category.slug})\n"
        f"CATEGORY DESCRIPTION: {category.description}\n\n"
        "This synthesis becomes the anchor for a weekly 'how does this "
        "week's reading update my thinking' digest. Lead with the most "
        "specific recurring claim or debate. Name the authors, products, "
        "datasets, and arguments that appear repeatedly. Generic "
        "statements that would apply to any reader of this category are "
        "useless — cut them.\n\n"
        f"{WRITING_STYLE}\n\n"
        "If the user has fewer than ~5 substantive bookmarks in this "
        "category, the corpus is too thin to write an honest baseline — "
        "call record_baseline_view with is_thin=true and an empty "
        "view_text.\n\n"
        "Always respond by calling the record_baseline_view tool."
    )


def _format_corpus(rows: list[tuple[str, str, str, str | None, str]]) -> str:
    parts = []
    for tweet_id, username, text, article, created_at in rows:
        snippet = (text or "").strip()
        if len(snippet) > 800:
            snippet = snippet[:800].rstrip() + "…"
        block = (
            f"---\nid: {tweet_id}\ndate: {created_at[:10]}\n"
            f"author: @{username}\ntext: {snippet}"
        )
        if article:
            article_snippet = article.strip()
            if len(article_snippet) > 1000:
                article_snippet = article_snippet[:1000].rstrip() + "…"
            block += f"\nlinked_article: {article_snippet}"
        parts.append(block)
    return "\n\n".join(parts)


def _estimate_cost(usage: Any) -> float:
    if not usage:
        return 0.0
    in_tokens = getattr(usage, "input_tokens", 0)
    out_tokens = getattr(usage, "output_tokens", 0)
    return (
        in_tokens / 1_000_000 * OPUS_INPUT_PER_MTOK
        + out_tokens / 1_000_000 * OPUS_OUTPUT_PER_MTOK
    )


async def _load_baseline_corpus(
    session: AsyncSession, category_id: int, cutoff: datetime
) -> list[tuple[str, str, str, str | None, str]]:
    """Bookmarks in this category older than `cutoff`."""
    stmt = (
        select(
            Bookmark.tweet_id,
            Author.username,
            BookmarkThread.full_thread_text.label("thread"),
            Tweet.text.label("leaf_text"),
            Tweet.article_text,
            Tweet.created_at,
        )
        .join(BookmarkClassification, BookmarkClassification.tweet_id == Bookmark.tweet_id)
        .join(Tweet, Tweet.tweet_id == Bookmark.tweet_id)
        .join(Author, Author.author_id == Tweet.author_id)
        .outerjoin(
            BookmarkThread,
            BookmarkThread.bookmark_tweet_id == Bookmark.tweet_id,
        )
        .where(BookmarkClassification.category_id == category_id)
        .where(Bookmark.bookmarked_at < cutoff)
        .order_by(Tweet.created_at.asc())
    )
    return [
        (tid, uname, thread or leaf or "", article, ca.isoformat() if ca else "")
        for tid, uname, thread, leaf, article, ca in (
            await session.execute(stmt)
        ).all()
    ]


async def latest_baseline(
    session: AsyncSession, category_id: int
) -> CategoryView | None:
    """Return the most recent CategoryView row for this category, if any."""
    return (
        await session.execute(
            select(CategoryView)
            .where(CategoryView.category_id == category_id)
            .order_by(desc(CategoryView.generated_at))
            .limit(1)
        )
    ).scalar_one_or_none()


async def needs_refresh(
    session: AsyncSession, category: Category, refresh_days: int
) -> bool:
    """Whether the baseline for this category is stale enough to regenerate."""
    if not category.enable_model_update:
        return False
    latest = await latest_baseline(session, category.id)
    if latest is None:
        return True
    age = datetime.now(timezone.utc) - latest.generated_at
    return age >= timedelta(days=refresh_days)


async def generate_baseline(
    session: AsyncSession,
    category: Category,
) -> CategoryView | None:
    """Generate a new baseline view for this category and persist it.

    Returns the new CategoryView, or None if the category isn't enabled or
    the corpus is too thin.
    """
    if not category.enable_model_update:
        logger.info(
            "Skipping baseline for %s — enable_model_update=false", category.slug
        )
        return None

    settings = get_settings()
    cutoff = datetime.now(timezone.utc) - timedelta(days=settings.BASELINE_AGE_DAYS)
    rows = await _load_baseline_corpus(session, category.id, cutoff)
    if len(rows) < settings.MIN_BASELINE_BOOKMARKS:
        logger.info(
            "Baseline corpus thin for %s: %d bookmarks (< %d)",
            category.slug,
            len(rows),
            settings.MIN_BASELINE_BOOKMARKS,
        )
        return None

    user_msg = (
        f"Here are {len(rows)} bookmarks the user has saved in this "
        "category, in chronological order, all older than the rolling "
        f"{settings.BASELINE_AGE_DAYS}-day interpretation window. Write "
        "their current view of the category.\n\n"
        f"BOOKMARKS:\n{_format_corpus(rows)}"
    )

    client = AsyncAnthropic(api_key=settings.ANTHROPIC_API_KEY)
    response = await client.messages.create(
        model=settings.OPUS_MODEL,
        max_tokens=2048,
        system=_system_prompt(category),
        tools=[BASELINE_TOOL],
        tool_choice={"type": "tool", "name": "record_baseline_view"},
        messages=[{"role": "user", "content": user_msg}],
    )

    cost = _estimate_cost(response.usage)
    async with session_scope() as cost_session:
        await log_api_call(
            cost_session,
            service="anthropic",
            endpoint=f"messages:{settings.OPUS_MODEL}:baseline",
            status_code=200,
            cost_usd=cost,
            tweets_returned=len(rows),
            notes=f"category={category.slug}",
        )

    tool_input: dict[str, Any] | None = None
    for block in response.content:
        if (
            getattr(block, "type", None) == "tool_use"
            and block.name == "record_baseline_view"
        ):
            tool_input = block.input  # type: ignore[assignment]
            break
    if tool_input is None:
        logger.warning(
            "Opus did not call record_baseline_view for %s. Got: %s",
            category.slug,
            json.dumps([b.model_dump() for b in response.content])[:300],
        )
        return None

    payload = _BaselinePayload.model_validate(tool_input)
    if payload.is_thin or not payload.view_text.strip():
        logger.info("Opus marked %s baseline as thin", category.slug)
        return None

    view = CategoryView(
        category_id=category.id,
        view_text=payload.view_text.strip(),
        source_bookmark_count=len(rows),
        source="auto",
        model=settings.OPUS_MODEL,
    )
    session.add(view)
    await session.flush()
    logger.info(
        "Generated baseline for %s (%d bookmarks, %d chars)",
        category.slug,
        len(rows),
        len(view.view_text),
    )
    return view


async def refresh_all_baselines(
    *,
    force: bool = False,
) -> dict[str, int]:
    """Regenerate baselines for every eligible category whose latest is stale."""
    settings = get_settings()
    refreshed = 0
    skipped = 0
    thin = 0
    async with session_scope() as session:
        cats = list(
            (
                await session.execute(
                    select(Category)
                    .where(Category.enable_model_update.is_(True))
                    .order_by(Category.sort_order, Category.id)
                )
            )
            .scalars()
            .all()
        )

    for cat in cats:
        async with session_scope() as session:
            cat = await session.get(Category, cat.id)
            if cat is None:
                continue
            if not force and not await needs_refresh(
                session, cat, settings.BASELINE_REFRESH_DAYS
            ):
                skipped += 1
                continue
            view = await generate_baseline(session, cat)
            if view is None:
                thin += 1
            else:
                refreshed += 1

    return {"refreshed": refreshed, "skipped": skipped, "thin_or_failed": thin}
